In [10]:
import pandas as pd
import numpy as np

In [2]:
se = pd.Series([1,2,np.nan,4])
se

0    1.0
1    2.0
2    NaN
3    4.0
dtype: float64

In [3]:
se.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [4]:
list1 = [1,2,None,4]
se = pd.Series(list1, index=['A','B','C','D'])
print(se)

A    1.0
B    2.0
C    NaN
D    4.0
dtype: float64

In [5]:
se['A']

np.float64(1.0)

In [6]:
month_se = pd.Series(['1월', '2월','3월','4월'])
income_se = pd.Series([9500,6200,6050,7000])
expenses_se = pd.Series([5040, 2350, 2300, 4800])
df = pd.DataFrame( {'월': month_se, '수익': income_se, '지출':expenses_se})
df

    월    수익    지출
0  1월  9500  5040
1  2월  6200  2350
2  3월  6050  2300
3  4월  7000  4800

In [7]:
print(df)

    월    수익    지출
0  1월  9500  5040
1  2월  6200  2350
2  3월  6050  2300
3  4월  7000  4800

In [8]:
(df.columns)[0]

'월'

In [11]:
np.argmax(df['수익'])

np.int64(0)

In [14]:
df['수익'][0]

np.int64(9500)

In [15]:
df['수익'][np.argmax(df['수익'])]

np.int64(9500)

In [16]:
income_se.max()

np.int64(9500)

In [17]:
income_se.min()

np.int64(6050)

In [18]:
income_se.mean()

np.float64(7187.5)

In [20]:
file = '../csv/vehicle_prod.csv'
df = pd.read_csv(file)

In [21]:
df

  Unnamed: 0   2007   2008   2009   2010   2011
0      China   7.71   7.95  11.96  15.84  16.33
1         EU  19.02  17.71  15.00  16.70  17.48
2         US  10.47   8.45   5.58   7.60   8.40
3      Japan  10.87  10.83   7.55   9.09   7.88
4      Korea   4.04   3.78   3.45   4.20   4.62
5     Mexico   2.01   2.05   1.50   2.25   2.54